project_id = "zwbhlfhwymbmvioaikvs"

[functions.suno-callback]
verify_jwt = false

[functions.test-suno-connection]
verify_jwt = false

[functions.update-processing-status]
verify_jwt = false

[functions.generate-suno-lyrics]
verify_jwt = true

[functions.get-suno-lyrics-info]
verify_jwt = true

[functions.upload-extend-suno-track]
verify_jwt = true

[functions.get-suno-timestamped-lyrics]
verify_jwt = true

[functions.convert-suno-to-wav]
verify_jwt = true

[functions.get-suno-wav-info]
verify_jwt = true

[functions.separate-suno-vocals]
verify_jwt = true

[functions.get-suno-vocal-separation-info]
verify_jwt = true