project_id = "zwbhlfhwymbmvioaikvs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://zwbhlfhwymbmvioaikvs.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54327

[functions.delete-track]
verify_jwt = true

[functions.sync-track-storage]
verify_jwt = true

[functions.telegram-auth]
verify_jwt = false

[functions.suno-callback]
verify_jwt = false

[functions.test-suno-connection]
verify_jwt = false

[functions.update-processing-status]
verify_jwt = false

[functions.generate-suno-lyrics]
verify_jwt = true

[functions.get-suno-lyrics-info]
verify_jwt = true

[functions.upload-extend-suno-track]
verify_jwt = true

[functions.get-suno-timestamped-lyrics]
verify_jwt = true

[functions.convert-suno-to-wav]
verify_jwt = true

[functions.get-suno-wav-info]
verify_jwt = true

[functions.separate-suno-vocals]
verify_jwt = true

[functions.get-suno-vocal-separation-info]
verify_jwt = true

[functions.recover-suno-tracks]
verify_jwt = true

[functions.reset-user-data]
verify_jwt = true
