// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpvzmjnnrwoatjeynizt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwdnptam5ucndvYXRqZXluaXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MDcwOTYsImV4cCI6MjA3NzQ4MzA5Nn0.7QkaIbderjH3ZN-GS8C_7Or3oNeBJKEzMYSKt2ULfig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});